steps:
# Note we mount the ssh directory from steps above within the build workspace so that the Dockerfile can see it
- name: 'docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/backend:$SHORT_SHA', 'gcr.io/$PROJECT_ID/backend:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/backend:$SHORT_SHA', 'gcr.io/$PROJECT_ID/backend:$BRANCH_NAME']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/backend:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/backend:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/backend:$BRANCH_NAME']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'beta', 'run', 'deploy', '--region', 'europe-west1', '--image', 'gcr.io/$PROJECT_ID/backend', '--platform', 'managed', 'backend-$BRANCH_NAME' ]
images:
- 'gcr.io/$PROJECT_ID/backend'
